# Generated by Django 5.2.1 on 2025-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_address_customuser_birth_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_year',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
