# Generated by Django 5.2.1 on 2025-06-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_birth_year_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
