# Generated by Django 5.2.1 on 2025-06-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_phone_number_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
