# Generated by Django 5.2.1 on 2025-06-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reservation_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
