# Generated by Django 5.2.1 on 2025-06-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reservation_is_hidden_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='connector_type',
            field=models.CharField(choices=[('Type 2', 'Type 2'), ('CCS', 'CCS'), ('CHAdeMO', 'CHAdeMO')], default='Type 2', max_length=50),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='power_kw',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='price_per_kwh',
            field=models.FloatField(default=1.5),
        ),
    ]
